### ISSUE TITLE
 Host 模式试试的错误。

### ISSUE THREAD

**Issue by piaohailin** [ygqygq2/fastdfs-nginx#16]
环境Mac Desktop Docker，镜像版本：ygqygq2/fastdfs-nginx:V6.11.0
在容器内测试成功，可以上传文件，可以用127.0.0.1浏览

因为容器内无法用应用程序链接，采用network_mode: host模式。
容器内报错如下：
**1、tracker容器**
[2024-02-28 01:05:19] INFO - FastDFS v6.11.0, base_path=/var/fdfs, max_connections=1024, connect_timeout=5, network_timeout=60, thread_stack_size=256 KB, max_pkg_size=256 KB, min_buff_size=8 KB, max_buff_size=256 KB, tcp_quick_ack=1, log_level=INFO, run_by_group=, run_by_user=, error-log: {sync_log_buff_interval=1, rotate_everyday=1, rotate_time=00:00, rotate_on_size=0, compress_old=0, compress_days_before=1, keep_days=0, delete_old_time=01:30}, port=22122, bind_addr=, address_family=auto, accept_threads=1, work_threads=4, store_lookup=2, store_group=, store_server=0, store_path=0, reserved_storage_space=20.00%, download_server=0, allow_ip_count=-1, check_active_interval=120s, storage_ip_changed_auto_adjust=1, storage_sync_file_max_delay=86400s, storage_sync_file_max_time=300s, use_trunk_file=0, slot_min_size=256, slot_max_size=1024 KB, trunk_alloc_alignment_size=256, trunk_file_size=64 MB, trunk_create_file_advance=0, trunk_create_file_time_base=02:00, trunk_create_file_interval=86400, trunk_create_file_space_threshold=20 GB, trunk_init_check_occupying=0, trunk_init_reload_from_binlog=0, trunk_free_space_merge=1, delete_unused_trunk_files=0, trunk_compress_binlog_min_interval=86400, trunk_compress_binlog_interval=86400, trunk_compress_binlog_time_base=03:00, trunk_binlog_max_backups=7, use_storage_id=0, id_type_in_filename=ip, trust_storage_server_id=1, storage_id/ip_count=0 / 0, store_slave_file_use_link=0, use_connection_pool=0, g_connection_pool_max_idle_time=3600s
kill pid: 18 fail, errno: 3, error info: No such process
**2、storage容器**
ngx_http_fastdfs_set pid=14
pid file: /var/fdfs/data/fdfs_storaged.pid not exist!
try to start the storage node...
[2024-02-28 01:05:06] ERROR - file: fdfs_shared_func.c, line: 496, host "tracker" is invalid, error info: Unknown host
[2024-02-28 01:05:06] CRIT - exit abnormally!

**Comment by ygqygq2** [comment]
给你个示例，因为使用 host 网络，就无法解析 tracker 这种service 名，所以要添加 hosts

```yaml
version: '3'
#networks:
#  fastdfs-net:
#    external: true
#networks:
#  fastdfs-net:
#    driver: bridge
services:
  tracker:
    container_name: tracker
    image: ygqygq2/fastdfs-nginx:latest
    command: tracker
    #network_mode: host
    #networks:
    #  - fastdfs-net
    volumes:
      - /var/fdfs/tracker:/var/fdfs
    ports:
      - 22122:22122
  storage0:
    container_name: storage0
    image: ygqygq2/fastdfs-nginx:latest
    command: storage
    network_mode: host
    extra_hosts:
      - "tracker:内网IP（别用127.0.0.1）"
    #networks:
    #  - fastdfs-net
    environment:
      - TRACKER_SERVER=tracker:22122
    volumes:
      - /var/fdfs/storage0:/var/fdfs
    ports:
      - 28080:8080
    depends_on:
      - tracker
```
