### ISSUE TITLE
Docker Host模式无法连通

### ISSUE THREAD

**Issue by ukid** [ygqygq2/fastdfs-nginx#7]
docker-compose.yml
````
version: "3.7"

services:
  tracker:
    container_name: tracker
    image: ygqygq2/fastdfs-nginx
    command: tracker
    network_mode: host
    volumes:
      - ./tracker:/var/fdfs

  storage0:
    container_name: storage0
    image: ygqygq2/fastdfs-nginx
    command: storage
    network_mode: host
    environment:
      - TRACKER_SERVER=192.168.50.244:22122
    volumes:
      - ./storage0:/var/fdfs
````
进入storage查看日志，测试端口状态
````
[2019-05-16 03:54:02] ERROR - file: storage_ip_changed_dealer.c, line: 186, connect to tracker server 192.168.50.244:22122 fail, errno: 111, error info: Connection refused
[2019-05-16 03:54:17] ERROR - file: storage_ip_changed_dealer.c, line: 186, connect to tracker server 192.168.50.244:22122 fail, errno: 111, error info: Connection refused
^C
[root@linuxkit-025000000001 fastdfs-nginx-module]# curl http://localhost:8080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to tengine!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to tengine!</h1>
<p>If you see this page, the tengine web server is successfully installed and
working. Further configuration is required.</p>
````
容器中8080是可以访问的，宿主机无法访问容器8080端口。疑似容器中的(tracker,storage,nginx)网络监听都绑定到了127.0.0.1上。

求大佬助攻。
